flight_scoreboard/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()
router.register('flight', views.ApiFlightViewSet, base_name='flight')

urlpatterns = router.urls

flight_scoreboard/flight/urls.py
from django.conf.urls import url
from flight import views


app_name = 'flight'
urlpatterns = [
    url(r'^flight/new/$', views.new_flight, name="new_flight"),
    url(r'^flight/(?P<flight_id>[0-9]+)/$', views.flight_view, name="flight_edit"),
    url(r'^flight/delete/(?P<flight_id>[0-9]+)/$', views.delete_flight, name="delete_flight"),
    url(r'^', views.index, name="index"),
]

flight_scoreboard/flight_scoreboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Flight scoreboard API')

urlpatterns = [
    url(r'^swagger_api/', schema_view),
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include("api.urls")),
    url('', include("flight.urls")),
]

flight_scoreboard/api/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

flight_scoreboard/flight/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Flight(models.Model):
    STATUS = (
        (None, 'Выберите статус'),
        ('v', 'Вылетел'),
        ('p', 'Приземлился'),
        ('i', 'Идет посадка'),
        ('z ', 'Задержан'),

    )

    number = models.TextField(verbose_name='Номер рейса')
    departure_city = models.ForeignKey('City', verbose_name='Город вылета', related_name='input_flights')
    arrival_city = models.ForeignKey('City', verbose_name='Город прибытия', related_name='output_flights')
    plane_type = models.ForeignKey('Airbus', verbose_name='Тип самолета')
    planned_departure_time = models.DateTimeField(verbose_name='Плановая дата и время вылета')
    planned_arrival_time = models.DateTimeField(verbose_name='Плановая дата и время прилета')
    actual_departure_time = models.DateTimeField(null=True, blank=True, verbose_name='Фактическая дата и время вылета',
                                                 default=None)
    actual_arrival_time = models.DateTimeField(null=True, blank=True, verbose_name='Фактическая дата и время прилета',
                                               default=None)
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус рейса')

    class Meta:
        verbose_name_plural = 'Рейсы'
        verbose_name = 'Рейс'
        ordering = ['planned_departure_time']

    def __str__(self):
        return "%s %s %s" %(self.number, self.departure_city.name, self.arrival_city.name)


@python_2_unicode_compatible
class City(models.Model):
    name = models.TextField(verbose_name='Город')

    class Meta:
        verbose_name_plural = 'Города'
        verbose_name = 'Город'

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Airbus(models.Model):
    type_plane = models.TextField(verbose_name='Тип самолета')

    class Meta:
        verbose_name_plural = 'Типы самолетов'
        verbose_name = 'Тип самолета'

    def __str__(self):
        return self.type_plane

flight_scoreboard/flight/forms.py
# coding=utf-8
from django import forms

from flight.models import Flight, City, Airbus


class SearchFlightsForm(forms.Form):
    city_departure = forms.ModelChoiceField(queryset=City.objects.all(), label='Город вылета', required=False)
    city_arrival = forms.ModelChoiceField(queryset=City.objects.all(), label='Город прилёта', required=False)
    status = forms.ChoiceField(choices=Flight.STATUS, label='Статус', required=False)

    class Meta:
        fields = ('city_departure', 'city_arrival', 'status')


class FlightForm(forms.ModelForm):
    departure_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город вылета')
    arrival_city = forms.ModelChoiceField(queryset=City.objects.all(), label='Город прилёта')
    plane_type = forms.ModelChoiceField(queryset=Airbus.objects.all(), label='Тип самолёта')

    class Meta:
        model = Flight
        fields = (
            'number',
            'departure_city',
            'arrival_city',
            'status',
            'plane_type',
            'planned_departure_time',
            'planned_arrival_time',
            'actual_departure_time',
            'actual_arrival_time',
        )

flight_scoreboard/api/views.py
from django.shortcuts import render
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import AllowAny
from flight.models import Flight
from api.serializers import FlightSerializer


class ApiFlightViewSet(ModelViewSet):
    queryset = Flight.objects.all()
    serializer_class = FlightSerializer
    permission_classes = [AllowAny]

flight_scoreboard/flight/views.py
# coding=utf-8
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods

from flight.models import Flight
from flight.forms import SearchFlightsForm, FlightForm


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'POST':
        search_form = SearchFlightsForm(request.POST)
        if search_form.is_valid():
            search_data = {}
            if search_form.cleaned_data['city_departure']:
                search_data['departure_city'] = search_form.cleaned_data['city_departure'].id
            if search_form.cleaned_data['city_arrival']:
                search_data['arrival_city'] = search_form.cleaned_data['city_arrival'].id
            if search_form.cleaned_data['status']:
                search_data['status'] = search_form.cleaned_data['status']
            flights = Flight.objects.filter(**search_data)
        else:
            flights = Flight.objects.all()
    else:
        search_form = SearchFlightsForm()
        flights = Flight.objects.all()

    data = {
        'search_form': search_form,
        'flights': flights
    }
    return render(request, 'index.html', context=data, status=200)


@require_http_methods(['GET', 'POST'])
def flight_view(request, flight_id):
    flight = get_object_or_404(Flight, pk=flight_id)
    flight_form = FlightForm(request.POST or None, instance=flight)
    if request.method == 'POST':
        if flight_form.is_valid():
            flight_form.save()
            return redirect("flight:index")
    return render(request, "flight.html", {'flight_form': flight_form, 'flight': flight})


@require_http_methods(['GET', 'POST'])
def new_flight(request):
    if request.method == 'POST':
        flight_form = FlightForm(request.POST)
        if flight_form.is_valid():
            flight_form.save()
            return redirect('flight:index')
        return render(request, 'flight.html', {'flight_form': flight_form, 'flight': None})
    flight_form = FlightForm()
    return render(request, 'flight.html', {'flight_form': flight_form, 'flight': None})


@require_http_methods(['POST', 'GET'])
def delete_flight(request, flight_id):
    flight = get_object_or_404(Flight, pk=flight_id)
    if request.method == 'POST':
        flight.delete()
        messages.add_message(request, messages.SUCCESS, 'Рейс удален')
        return redirect('flight:index')
    else:
        return render(request, 'flight_delete_confirm.html', {'flight_id': flight_id})

flight_scoreboard/flight/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <title>&#9992;Сибирские авиалинии</title>
</head>
<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <div class="row">
                <div class="col-12">
                     <h1 class="mb-2 mt-2">{% block header_text %}{% endblock %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {% block content %}{% endblock %}
                </div>
            </div>


        </div>
    </main>

</body>
</html>

flight_scoreboard/flight/templates/flight.html
{% extends 'base.html' %}
    {% block header_text %}{% if not flight  %}Создать рейс{% else %}Изменить рейс{% endif %}{% endblock %}
{% block content %}
    {% for error in flight_form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                      {{ flight_form.image.errors }}
                  </div>
                {% endfor %}
`
                <form method="post" action="{% if not flight  %}
                                                {% url 'flight:new_flight' %}
                                            {% else %}
                                                {% url 'flight:flight_edit' flight_id=flight.id %}
                                            {% endif %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in flight_form %}
                        <div class="form-group row" aria-required='{% if field.field.required %}"true"{% else %}"false"{% endif %}'>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                                    {{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                                </label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field }}

<!--                                    {% if field.help_text %}-->
<!--                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>-->
<!--                                    {% endif %}-->
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% if not flight %}Добавить{% else %}Сохранить{% endif %}
                            </button>
                    {% if flight %}
                            <a href="{% url 'flight:delete_flight' flight_id=flight.id %}" class="btn btn-outline-danger">
                                Удалить
                            </a>
                    {% endif %}
                    </div>
                </form>
{% endblock %}

flight_scoreboard/flight/templates/flight_delete_confirm.html
{% extends 'base.html' %}
    {% block header_text %}Удаление рейса{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Удалить">
    <a href="{% url 'flight:index' %}" class="btn btn-outline-primary">
                                Отмена
                            </a>
    </form>
{% endblock %}

flight_scoreboard/flight/templates/index.html
{% extends 'base.html' %}
    {% block header_text %}Табло рейсов{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12 mb-2 mt-2">
            <b>Всего рейсов:</b>
            <span>{{ flights.count }}</span>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ search_form }}
        <input class="btn btn-outline-primary" type="submit" value="Поиск">
    </form>
    <table class="table mt-3">
    <thead>
        <tr>
            <th scope="col">Номер рейса</th>
            <th scope="col">Город вылета</th>
            <th scope="col">Город прилёта</th>
            <th scope="col">Тип самолёта</th>
            <th scope="col">Дата и Время вылета</th>
            <th scope="col">Дата и Время прибытия</th>
            <th scope="col">Статус</th>
            <th scope="col"></th>
        </tr>
    </thead>
    {% for flight in flights %}
        <tr>
            <td>{{ flight.number }}</td>
            <td>{{ flight.departure_city }}</td>
            <td>{{ flight.arrival_city }}</td>
            <td>{{ flight.plane_type }}</td>
            <td>{{ flight.planned_departure_time|date:"d.m.Y H:i" }} мск</td>
            <td>{{ flight.planned_arrival_time|date:"d.m.Y H:i" }} мск</td>
            <td>{{ flight.get_status_display }}</td>
            <td><a class="btn btn-sm text-muted" href="{% url 'flight:flight_edit' flight.id %}"
                        role="button">
                        Редактировать
                </a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

flight_scoreboard/flight/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:dodgerblue">&#9992;Сибирские авиалинии</span></a>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 btn btn-outline-primary" href="{% url 'flight:new_flight' %}">Новый рейс</a>
    </nav>
</nav>